timestamp-file: '/Users/fgeller/.config/feeder/timestamps.yml'
email-template-file: '/Users/fgeller/.config/feeder/email.tmpl'
feeds-file: '/Users/fgeller/.config/feeder/feeds.yml'
email:
  from: example@gmail.com
  smtp:
    host: smtp.gmail.com
    port: 587
    user: example@gmail.com
    pass: passwort
